version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - GLOBUS_CLIENT_ID=${GLOBUS_CLIENT_ID}
      - GLOBUS_CLIENT_SECRET=${GLOBUS_CLIENT_SECRET}
      - GLOBUS_CONFIG_PATH=/home/globus/globus_config
    volumes:
      - .:/app
      - globus_config:/home/globus/globus_config
      - globus_data:/home/globus/data
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
          - /dev/net/tun:/dev/net/tun
    privileged: true
    platform: linux/amd64
    

volumes:
  globus_config:
  globus_data: 
  