version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - GLOBUS_CLIENT_ID=${GLOBUS_CLIENT_ID}
      - GLOBUS_CLIENT_SECRET=${GLOBUS_CLIENT_SECRET}
    volumes:
      - .:/app
    restart: unless-stopped 