version: "3.3"

services:
  globus-connect:
    build:
      context: .
      dockerfile: Dockerfile # Ensure Dockerfile.globus-connect is in the correct path
    container_name: globus_connect_container
    environment:
      - NGROK_AUTH_TOKEN=${NGROK_AUTH_TOKEN}
      - GLOBUS_CLIENT_ID=${GLOBUS_CLIENT_ID}
      - GLOBUS_CLIENT_SECRET=${GLOBUS_CLIENT_SECRET}
      - DataPath=${DataPath} # Ensure DataPath is set in the environment or .env file
      - ConfigPath=${ConfigPath} # Ensure ConfigPath is set in the environment or .env file
      - START_GLOBUS=false
    volumes:
      - "${ConfigPath}:/home/gridftp/globus_config" # Map host config path to container
      - shared-data:/shared-data # Shared volume between services
      - globus-data:/home/gridftp/data # Second shared volume specifically for /home/gridftp/data
    networks:
      - app-network
    ports:
      - "2811:2811" # Port mappings for Globus Connect
      - "7512:7512"
      - "2223:2223"
      - "7513:7513"
      - "5000:5000"
      - "50000:51000"
      - "443:443"
    restart: unless-stopped # Automatically restart unless stopped manually

volumes:
  shared-data:
    driver: local # Using local volume driver for shared-data
  globus-data:
    driver: local
    driver_opts:
      type: none
      device: ${DataPath}
      o: bind

networks:
  app-network:
    driver: bridge # Using bridge network driver for inter-container communication
